### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by ifsheldon** [JonasKruckenberg/k23#154]
https://github.com/JonasKruckenberg/k23/blob/1a79774d5d4f73ebc73eaf3822b44a31b6909896/manual/src/wasm/supported_features_and_proposals.md?plain=1#L77

Hi, I think there's a typo. `WASM` should be `WASI`.

**Comment by JonasKruckenberg** [comment]
Oh yeah good catch! Want to open a PR and get an easy contribution? :)

**Comment by ifsheldon** [comment]
You are welcome. No need for a handle. It's just a cup of coffee. I really like your ideas about k23, but I don't have time to dig into kernel development, so a cup of coffee is the least I can do for this project.

**Comment by JonasKruckenberg** [comment]
Well then, your support is much appreciated!
